[package]
name = "cook_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cook"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.40", features = ["derive", "env"] }
cook = { path = "../cook" }
kdl = { path = "../kdl" }
